### ISSUE TITLE
Finds as function calls in text strings that look like function calls

### ISSUE THREAD

**Issue by 9mjb** [koknat/callGraph#10]
python
def function_name():
   print('Trace: Called function_name()') # ERROR.. this will show as a function call when it is just a string

**Comment by koknat** [comment]
Sorry, but I don't have bandwidth to add special handling for the corner case of function_name() within a constant string.
It may work correctly if your print statement doesn't include the '()' at the end of 'Called function_name()'
Alternately, you could preprocess your .py script before running it through callGraph, to do the same.

**Comment by 9mjb** [comment]
That's what I started doing... omitting the ().
Thanks for the attention. (again) :-) .. I wanted to make sure you knew of
the issue.

**Comment by koknat** [comment]
Closing as there is a workaround for this corner case
