### ISSUE TITLE
javascript's fat arrow functions support

### ISSUE THREAD

**Issue by raphaelSeguin** [koknat/callGraph#16]
Hi,
it doesn't seem to support fat arrow functions in javascript.
My code looks like this:
```
const setOrderItems = (formItems) => {
```
callGraph: *ERROR: Could not find any function definitions in your file*

**Comment by koknat** [comment]
Hi Raphael,
Sorry, but callGraph doesn't support fat arrow functions or anonymous functions

**Comment by raphaelSeguin** [comment]
Hi Chris,
Thanks for your answer. I should try to do it myself.
