### ISSUE TITLE
Could it generate file level dependency?

### ISSUE THREAD

**Issue by happyhebaby** [koknat/callGraph#17]
Hi, I have two questions around the tool, thanks for your info.

1. Does it generate json or xml format output that could be consumed by code?
2. Does it generate file level dependency with corresponding file path info? For example `flask` repo has a test file `tests/test_appctx.py` that has the following import statements:
```
import pytest
import flask
from flask.globals import app_ctx
from flask.globals import request_ctx
```
I am looking for output of file level dependency like the following:
```
"tests.test_appctx": {
    "imports": [
      "flask",
      "flask.globals",
      "pytest"
    ],
    "name": "tests.test_appctx",
    "path": "/Users/myuserid/python/flask/tests/test_appctx.py"
  },

**Comment by koknat** [comment]
1) There is a new option for producing json: -jsnOut filename
It works similar to the existing option: -ymlOut filename

2) It does not parse 'import' or 'from' statements.  It only parses function definitions and calls

**Comment by happyhebaby** [comment]
Thank you!
