### ISSUE TITLE
language fortran is not supported

### ISSUE THREAD

**Issue by kerneltravel** [koknat/callGraph#22]
```
ERROR:  Language '' not recognized.  Specify it with  -language <language>
        For example:  -language pl
        For example:  -language py
        For example:  -language tcl
        Supported languages are:  awk bas c cpp dart for go java jl js kt lua m pas php pl py r rb rs sc sh swift tcl ts v
```

**Comment by koknat** [comment]
Could you please provide a test case?  
Need the filename and file contents

**Comment by kerneltravel** [comment]
> Could you please provide a test case? Need the filename and file contents

a realworld case is `https://gitlab.com/octopus-code/octopus/-/raw/main/src/main/main.F90` file ,the main.F90 is the entrance file of octopus  sources.

**Comment by koknat** [comment]
It didn't recognize the .F90 extension.
That is fixed.
Please let me know if this test case works now:
```
cd octopus-main/src/main
callGraph *.F90 -start main.F90:__MAIN__
```

**Comment by kerneltravel** [comment]
> this test case works now

well,  this test case works now.

**Comment by kerneltravel** [comment]
![casida F90](https://github.com/koknat/callGraph/assets/437879/fb5444c3-babb-4ab5-bbd6-d1235073c404)
