### ISSUE TITLE
Feature request: support for the Julia language

### ISSUE THREAD

**Issue by amizeranschi** [koknat/callGraph#3]
Hi and thanks for this useful tool!

Given that so many languages are supported, including R and Python, would it be possible to add support for Julia as well?

**Comment by koknat** [comment]
Hi,

I'd be happy to add Julia support
Could you point me to an example .jl file on the web, which has many
function calls?

**Comment by amizeranschi** [comment]
Here are a couple of examples from Plots.jl and CUDA.jl, respectively:

https://github.com/JuliaPlots/Plots.jl/blob/master/src/utils.jl
https://github.com/JuliaGPU/CUDA.jl/blob/master/src/array.jl

I hope these will be helpful and thanks for looking into this.

**Comment by koknat** [comment]
Thanks, this is very helpful

What does it mean when a function has '!'
Base.push! is repeated in plots.jl:

function Base.push!(segments::Segments{T}, vs...) where {T}
    if !isempty(segments.pts)
        push!(segments.pts, to_nan(T))
    end
    for v in vs
        push!(segments.pts, convert(T, v))
    end
    segments
end

function Base.push!(segments::Segments{T}, vs::AVec) where {T}
    if !isempty(segments.pts)
        push!(segments.pts, to_nan(T))
    end
    for v in vs
        push!(segments.pts, convert(T, v))
    end
    segments
end

**Comment by amizeranschi** [comment]
See:
https://stackoverflow.com/questions/45396685/what-does-an-exclamation-mark-mean-after-the-name-of-a-function

**Comment by koknat** [comment]
Thanks

One final question:
I need to construct a regex that detects Julia function names
For most languages, this include a-z A-Z 0-9 and _
For Julia, I'm adding . and $ and !
I realize that it supports a wide range of unicode, but that may be too
complex for a regex.
Are there any other important characters that I'm missing?

**Comment by amizeranschi** [comment]
I'm not sure what to say here, I'm afraid. I'm no Julia expert by any means
and there seems to be a style naming guide (
https://docs.julialang.org/en/v1/manual/style-guide/), but a Google search
also revealed several people who seem to contest it, for subjective
reasons, so there's that.

Your suggestion seems fine for a start, so perhaps people can improve
things through issue reports in needed.

**Comment by koknat** [comment]
I've uploaded the Julia update
Please let me know how it goes
