### ISSUE TITLE
Scan all files in (sub)folder(s)

### ISSUE THREAD

**Issue by some-avail** [koknat/callGraph#4]
It seems a nice tool with the graph and all.
Would it be an interesting feature to scan all files (of a certain language) in a folder (and if wished all subfolders?). 
It would require to generate a list of all functions per file per folder, as well as a list of all function-calls per function.
I was thinking of programming something like that my self but i am still in the phase of "make or find".

**Comment by koknat** [comment]
It already has similar functionality, but does not scan recursively into subfolders:
cd <directory>
callGraph *.extension -ymlOut functions.yml

**Comment by koknat** [comment]
I have added functionality to scan all files (of a certain language) in a folder and all subfolders.
For example:
callGraph <directory> -language php

**Comment by koknat** [comment]
Closing as feature is implemented Jan 4
