### ISSUE TITLE
Specify path + function name with -start option

### ISSUE THREAD

**Issue by niklr** [koknat/callGraph#6]
Hello @koknat thank you very much for this tool!

Is it somehow possible to specify the path to the file in combination with the function name in the -start option? 
e.g. `./callGraph . -start 'src/subfolder/main.go#update' -language 'go'`

I would like to generate a call graph for a specific function but the same name is used in different files of my application.

**Comment by koknat** [comment]
Assuming that the filename is 'main.go', and the function name is 'update', this should work:
./callGraph . -start 'src/subfolder/main.go:update' -language 'go'
or
./callGraph . -start 'main.go:update' -language 'go'

**Comment by niklr** [comment]
Awesome, this works indeed. Thank you @koknat!
