### ISSUE TITLE
Vaporware?

### ISSUE THREAD

**Issue by 9mjb** [koknat/callGraph#7]
No code?  Is this a test set?

**Comment by koknat** [comment]
It's the code.
The executable is 'callGraph'

**Comment by 9mjb** [comment]
Wow.  I've been seeing .py too long... and can't recognize a program anymore.  Plus GitHub isn't doing directory listings that have some information showing what is executable. Sorry.  Thanks for responding.  I'll check it out.

**Comment by koknat** [comment]
closing issue as 'not a bug'
